name: Test Play-Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os:
        - "ubuntu-latest"
        - "macos-latest"
        - "windows-latest"
        version:
        - "1.22"
        - "1.23"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}

    - name: Test
      run: go test -v ./...
